# Generated by Django 5.0.6 on 2024-07-04 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=8, null=True)),
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('unidad', models.CharField(max_length=20)),
                ('cantidad_stock', models.IntegerField(blank=True, null=True)),
                ('cantidad_inventario', models.IntegerField(blank=True, null=True)),
                ('ingresado', models.DateTimeField(auto_now=True)),
                ('costo_compra', models.IntegerField(blank=True, null=True)),
                ('costo_venta', models.IntegerField(blank=True, null=True)),
                ('clase1', models.CharField(max_length=200)),
                ('clase2', models.CharField(max_length=200)),
                ('bodega', models.CharField(max_length=100)),
                ('proveedor', models.CharField(max_length=300)),
                ('descripcion', models.CharField(max_length=500)),
                ('obsoleto', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_id', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_inventario', models.IntegerField(blank=True, null=True)),
                ('fecha_inventario', models.DateTimeField(auto_now_add=True)),
                ('observacion', models.CharField(max_length=500)),
                ('usuario', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_id_inv', to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, related_name='producto', to='base.producto')),
            ],
        ),
    ]
