# Generated by Django 5.0.6 on 2024-06-03 21:52

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=50, verbose_name=django.contrib.auth.models.AbstractUser)),
                ('codigo', models.CharField(blank=True, max_length=8, null=True)),
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('unidad', models.CharField(max_length=20)),
                ('cantidad_stock', models.IntegerField(blank=True, null=True)),
                ('cantidad_inventario', models.IntegerField(blank=True, null=True)),
                ('ingresado', models.DateTimeField(auto_now=True)),
                ('costo_compra', models.IntegerField(blank=True, null=True)),
                ('costo_venta', models.IntegerField(blank=True, null=True)),
                ('clase1', models.CharField(max_length=200)),
                ('clase2', models.CharField(max_length=200)),
                ('bodega', models.CharField(max_length=100)),
                ('proveedor', models.CharField(max_length=300)),
                ('descripcion', models.CharField(max_length=500)),
                ('obsoleto', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
